"""initial warehouse schema

Revision ID: 7ac13a4b5b9e
Revises: 
Create Date: 2026-06-24 19:09:33.621941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ac13a4b5b9e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dim_date',
    sa.Column('date_key', sa.Integer(), autoincrement=False, nullable=False, comment='Integer key in YYYYMMDD format'),
    sa.Column('full_date', sa.Date(), nullable=False, comment='Actual calendar date'),
    sa.Column('year', sa.SmallInteger(), nullable=False),
    sa.Column('quarter', sa.SmallInteger(), nullable=False, comment='1-4'),
    sa.Column('month', sa.SmallInteger(), nullable=False, comment='1-12'),
    sa.Column('month_name', sa.String(length=9), nullable=False, comment='January ... December'),
    sa.Column('month_short', sa.String(length=3), nullable=False, comment='Jan ... Dec'),
    sa.Column('week_of_year', sa.SmallInteger(), nullable=False, comment='ISO week number 1-53'),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False, comment='1=Monday ... 7=Sunday (ISO)'),
    sa.Column('day_name', sa.String(length=9), nullable=False, comment='Monday ... Sunday'),
    sa.Column('is_weekend', sa.Boolean(), nullable=False),
    sa.Column('fiscal_year', sa.SmallInteger(), nullable=True, comment='Set if fiscal year differs from calendar year'),
    sa.Column('fiscal_quarter', sa.SmallInteger(), nullable=True),
    sa.PrimaryKeyConstraint('date_key'),
    sa.UniqueConstraint('full_date')
    )
    op.create_table('dim_user',
    sa.Column('user_key', sa.String(length=36), nullable=False, comment='Matches users.id in Postgres'),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False, comment='user | super_admin'),
    sa.Column('account_ids', sa.String(length=65535), nullable=True, comment='JSON array of connected Google account UUIDs'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False if user was deactivated in the app'),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False, comment='Last sync from Postgres users table'),
    sa.PrimaryKeyConstraint('user_key')
    )
    op.create_table('dim_vendor',
    sa.Column('vendor_key', sa.String(length=36), nullable=False, comment='UUID surrogate key for the vendor'),
    sa.Column('sender_email', sa.String(length=255), nullable=False, comment='Gmail sender address e.g. receipts@stripe.com'),
    sa.Column('vendor_name', sa.String(length=255), nullable=True, comment='Human-readable name from config or email'),
    sa.Column('category', sa.String(length=100), nullable=True, comment='e.g. SaaS, Cloud, Marketing, Finance'),
    sa.Column('template_hash', sa.String(length=64), nullable=True, comment="SHA-256 of the sender's email HTML structure"),
    sa.Column('config_confidence', sa.Numeric(precision=4, scale=3), nullable=True, comment='0.000-1.000 LLM confidence in selectors'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='False if sender config was revoked or removed'),
    sa.Column('synced_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False, comment='Last sync from Postgres scraping_configs'),
    sa.PrimaryKeyConstraint('vendor_key'),
    sa.UniqueConstraint('sender_email')
    )
    op.create_table('fact_receipts',
    sa.Column('email_id', sa.String(length=32), nullable=False, comment='Gmail message ID — natural key for upsert'),
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='Matches dim_user.user_key'),
    sa.Column('vendor_key', sa.String(length=36), nullable=True, comment='FK to dim_vendor; null if unknown'),
    sa.Column('date_key', sa.Integer(), nullable=True, comment='YYYYMMDD of receipt date; null if unparseable'),
    sa.Column('account_id', sa.String(length=36), nullable=False, comment='Matches google_accounts.id in Postgres'),
    sa.Column('currency', sa.String(length=3), nullable=True, comment='ISO 4217 e.g. USD, INR'),
    sa.Column('amount', sa.Numeric(precision=14, scale=4), nullable=True, comment='Amount in `currency`'),
    sa.Column('tax', sa.Numeric(precision=14, scale=4), nullable=True, comment='Tax in `currency`'),
    sa.Column('total', sa.Numeric(precision=14, scale=4), nullable=True, comment='Total in `currency` — primary analytics field'),
    sa.Column('line_items', sa.String(length=65535), nullable=True, comment='Extracted line items array (JSON string)'),
    sa.Column('metadata', sa.String(length=65535), nullable=True, comment='Flexible per-receipt metadata as JSON string'),
    sa.Column('receipt_date', sa.Date(), nullable=True, comment='Date on the receipt'),
    sa.Column('email_date', sa.Date(), nullable=True, comment='Date the email was received'),
    sa.Column('invoice_number', sa.String(length=100), nullable=True, comment='Invoice/receipt number — degenerate dimension'),
    sa.Column('confidence_score', sa.Numeric(precision=4, scale=3), nullable=True, comment='0.000-1.000 extraction confidence'),
    sa.Column('extraction_status', sa.String(length=20), nullable=False, comment='extracted | quarantine | no_config | error'),
    sa.Column('anomaly_flag', sa.Boolean(), nullable=False, comment='True if amount is a statistical outlier'),
    sa.Column('anomaly_z_score', sa.Numeric(precision=8, scale=4), nullable=True, comment='Z-score of total within vendor+user window'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='Soft delete timestamp — null means active'),
    sa.Column('silver_id', sa.String(length=36), nullable=True, comment='silver_email_data.id this row was extracted from'),
    sa.Column('extracted_at', sa.DateTime(), nullable=True, comment='When extraction ran'),
    sa.Column('loaded_at', sa.DateTime(), server_default=sa.text('GETDATE()'), nullable=False, comment='When last written to the warehouse — ETL watermark'),
    sa.ForeignKeyConstraint(['date_key'], ['dim_date.date_key'], name='fk_receipts_date'),
    sa.ForeignKeyConstraint(['user_id'], ['dim_user.user_key'], name='fk_receipts_user'),
    sa.ForeignKeyConstraint(['vendor_key'], ['dim_vendor.vendor_key'], name='fk_receipts_vendor'),
    sa.PrimaryKeyConstraint('email_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fact_receipts')
    op.drop_table('dim_vendor')
    op.drop_table('dim_user')
    op.drop_table('dim_date')
    # ### end Alembic commands ###
